### ISSUE TITLE
sdk 路径错误

### ISSUE THREAD

**Issue by qbright** [tencentyun/imApiFlutterExample#1]
老哥上传demo需要仔细些
![QQ20210607-180206](https://user-images.githubusercontent.com/2003005/120998605-d1a49200-c7ba-11eb-9bd1-d38f881d2451.jpg)

**Comment by UniKylin** [comment]
tencent_im_sdk_plugin: 
    path: /Users/xingchenhe/Documents/work/Flutter/TencentImSDKPlugin


？？？

**Comment by UniKylin** [comment]
> tencent_im_sdk_plugin:
> path: /Users/xingchenhe/Documents/work/Flutter/TencentImSDKPlugin
> 
> ？？？

@hexingcheng thanks

**Comment by hexingcheng** [comment]
该路径为本地调试路径，换成pub上最新sdk的版本号即可
